# Generated by Django 6.0.1 on 2026-01-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_sql", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="reminder_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Напоминание"
            ),
        ),
    ]
