# Generated by Django 6.0.1 on 2026-01-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_sql", "0002_add_reminder_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["-is_pinned", "order", "-updated_at"],
                "verbose_name": "Заметка",
                "verbose_name_plural": "Заметки",
            },
        ),
        migrations.AddField(
            model_name="note",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
