# Generated by Django 6.0.1 on 2026-01-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_sql", "0002_note_reminder_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="is_archived",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="В архиве"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="is_pinned",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Закреплено"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="is_trashed",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="В корзине"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Дата обновления"
            ),
        ),
    ]
