# Generated by Django 6.0.1 on 2026-01-29 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_sql", "0003_alter_note_options_note_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checklistitem",
            options={
                "ordering": ["order"],
                "verbose_name": "Пункт чеклиста",
                "verbose_name_plural": "Пункты чеклиста",
            },
        ),
        migrations.AlterModelOptions(
            name="label",
            options={"verbose_name": "Метка", "verbose_name_plural": "Метки"},
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist_items",
                to="todo_sql.note",
                verbose_name="Заметка",
            ),
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="label",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="color",
            field=models.CharField(
                choices=[
                    ("white", "Белый"),
                    ("red", "Красный"),
                    ("orange", "Оранжевый"),
                    ("yellow", "Желтый"),
                    ("green", "Зеленый"),
                    ("teal", "Бирюзовый"),
                    ("blue", "Синий"),
                    ("darkblue", "Темно-синий"),
                    ("purple", "Фиолетовый"),
                    ("pink", "Розовый"),
                    ("brown", "Коричневый"),
                    ("gray", "Серый"),
                ],
                default="white",
                max_length=20,
                verbose_name="Цвет",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True, verbose_name="Содержимое"),
        ),
        migrations.AlterField(
            model_name="note",
            name="is_checklist",
            field=models.BooleanField(default=False, verbose_name="Режим чеклиста"),
        ),
        migrations.AlterField(
            model_name="note",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Порядок"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
