# Generated by Django 6.0.3 on 2026-03-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_sql", "0004_alter_checklistitem_options_alter_label_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={
                "ordering": ["name"],
                "verbose_name": "Метка",
                "verbose_name_plural": "Метки",
            },
        ),
    ]
