# Generated by Django 5.1 on 2026-01-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_sql", "0004_alter_task_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок"
                    ),
                ),
                ("content", models.TextField(verbose_name="Текст заметки")),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("red", "Red"),
                            ("orange", "Orange"),
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("teal", "Teal"),
                            ("blue", "Blue"),
                            ("darkblue", "Dark Blue"),
                            ("purple", "Purple"),
                            ("pink", "Pink"),
                            ("brown", "Brown"),
                            ("gray", "Gray"),
                        ],
                        default="white",
                        max_length=20,
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Закреплено"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Заметка",
                "verbose_name_plural": "Заметки",
                "ordering": ["-is_pinned", "-updated_at"],
            },
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
