server {
    listen 80;
    server_name your_domain.com; # Замените на ваш домен или IP

    location = /favicon.ico { access_log off; log_not_found off; }

    # Static files handled by Whitenoise in Django, but Nginx can also serve them directly if configured
    # We will let Whitenoise handle it for simplicity, or point alias to static root:
    # location /static/ {
    #     alias /var/www/todo_sql/staticfiles/;
    # }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
